[package]
name = "trash"
version = "0.1.0"
authors = ["Giuseppe Capizzi <g.capizzi@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"

[dev-dependencies]
expect = { git = "https://github.com/gcapizzi/expect.git" }
